### PR TITLE
Restrict accepted TLS ciphers

### PR DESCRIPTION
**Pull request by dyson**
Restrict the TLS ciphers PostgreSQL instances will accept to those
defined in the the Mozilla Intermediate compatibility sever
security guide:
https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29

This will restrict connections to only those using the TLS 1.2 and
TLS 1.3 protocol using the defined ciphers. Once TLS 1.3 is more
widely available, we could restrict the cipher list further.

The resulting cipher suites, according to `sslyze --sslv2 --sslv3
--tlsv1 --tlsv1_1 --tlsv1_2 --tlsv1_3 localhost:$PGPORT
--starttls=postgres --hide_rejected_ciphers --cert=$PGSSLCERT
--key=$PGSSLKEY`

 AVAILABLE PLUGINS
 -----------------

  SessionRenegotiationPlugin
  CertificateInfoPlugin
  HeartbleedPlugin
  RobotPlugin
  FallbackScsvPlugin
  HttpHeadersPlugin
  OpenSslCcsInjectionPlugin
  OpenSslCipherSuitesPlugin
  SessionResumptionPlugin
  CompressionPlugin

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   localhost:7463                      => 127.0.0.1

 SCAN RESULTS FOR LOCALHOST:7463 - 127.0.0.1
 -------------------------------------------

 * TLSV1_3 Cipher Suites:
      Server rejected all cipher suites.

 * TLSV1_1 Cipher Suites:
      Server rejected all cipher suites.

 * SSLV3 Cipher Suites:
      Server rejected all cipher suites.

 * SSLV2 Cipher Suites:
      Server rejected all cipher suites.

 * TLSV1_2 Cipher Suites:
       Forward Secrecy                    OK - Supported
       RC4                                OK - Not Supported

     Preferred:
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             ECDH-256 bits  128 bits
     Accepted:
        TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256       -              256 bits
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             ECDH-256 bits  256 bits
        TLS_DHE_RSA_WITH_AES_256_GCM_SHA384               DH-2048 bits   256 bits
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             ECDH-256 bits  128 bits
        TLS_DHE_RSA_WITH_AES_128_GCM_SHA256               DH-2048 bits   128 bits

 * TLSV1 Cipher Suites:
      Server rejected all cipher suites.

 SCAN COMPLETED IN 0.74 S
 ------------------------

sslyze had issues confirming the TLS 1.3 support however `psql -p
$PGPORT` shows it can connect with TLS 1.3:

psql (11.4 (Ubuntu 11.4-1.pgdg18.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)

postgres=#

### CODE REVIEW

**Comment by dyson** [comment]
Unfortunately TLS 1.3 isn't supported in OSX with it's LibreSSL:

```
:; openssl version
LibreSSL 2.6.5
:;  openssl ciphers -v 'TLSv1.3'
4656957036:error:14FFF0B9:SSL routines:(UNKNOWN)SSL_internal:no cipher match:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.260.1/libressl-2.6/ssl/ssl_lib.c:1324:
```

Support is better in openssl and (from reading) boringssl which is also widely used:
```
;: openssl version
OpenSSL 1.1.1  11 Sep 2018
:; openssl ciphers -v 'TLSv1.3'
TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
```

Once OSX by default supports TLS 1.3 in its openssl package we can drop the TLS 1.2 ciphers.

**Comment by benwh** [comment]
@dyson Can you run sslyze from within a Linux env, e.g. the Vagrant VM? That's what I did in #68, and should give us a view of the TLS1.3 settings.

**Comment by dyson** [comment]
That's what I did @benwh . Didn't work for me no matter what I tried 🤷‍♂ 😢

**Comment by benwh** [comment]
Ah from your message I thought you were running it just from MacOS, I get the same thing from sslyze on Linux, so forget about that then!

**Comment by benwh** [comment]
Here's the before and after, just looking at TLSv1.2 cipher suites:

*Before*:
```
Preferred:
   TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             ECDH-256 bits  256 bits

Accepted:
   ARIA128-GCM-SHA256                                -              128 bits
   ARIA256-GCM-SHA384                                -              256 bits
   DHE-RSA-ARIA128-GCM-SHA256                        -              128 bits
   DHE-RSA-ARIA256-GCM-SHA384                        -              256 bits
   DHE_RSA_WITH_AES_128_CCM                          -              128 bits
   DHE_RSA_WITH_AES_128_CCM_8                        -              128 bits
   DHE_RSA_WITH_AES_256_CCM_8                        -              256 bits
   ECDHE-ARIA128-GCM-SHA256                          -              128 bits
   ECDHE-ARIA256-GCM-SHA384                          -              256 bits
   RSA_WITH_AES_128_CCM                              -              128 bits
   RSA_WITH_AES_128_CCM_8                            -              128 bits
   RSA_WITH_AES_256_CCM                              -              256 bits
   RSA_WITH_AES_256_CCM_8                            -              256 bits
   TLS_DHE_RSA_WITH_AES_128_CBC_SHA256               DH-2048 bits   128 bits
   TLS_DHE_RSA_WITH_AES_128_GCM_SHA256               DH-2048 bits   128 bits
   TLS_DHE_RSA_WITH_AES_256_CBC_SHA256               DH-2048 bits   256 bits
   TLS_DHE_RSA_WITH_AES_256_CCM                      -              256 bits
   TLS_DHE_RSA_WITH_AES_256_GCM_SHA384               DH-2048 bits   256 bits
   TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256          -              128 bits
   TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256          -              256 bits
   TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256         -              256 bits
   TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256             ECDH-256 bits  128 bits
   TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             ECDH-256 bits  128 bits
   TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384             ECDH-256 bits  256 bits
   TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             ECDH-256 bits  256 bits
   TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256        -              128 bits
   TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384        -              256 bits
   TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256       -              256 bits
   TLS_RSA_WITH_AES_128_CBC_SHA256                   -              128 bits
   TLS_RSA_WITH_AES_128_GCM_SHA256                   -              128 bits
   TLS_RSA_WITH_AES_256_CBC_SHA256                   -              256 bits
   TLS_RSA_WITH_AES_256_GCM_SHA384                   -              256 bits
   TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256              -              128 bits
   TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256              -              256 bits
```

*After*:
```
Preferred:
   TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             ECDH-256 bits  128 bits

Accepted:
   TLS_DHE_RSA_WITH_AES_128_GCM_SHA256               DH-2048 bits   128 bits
   TLS_DHE_RSA_WITH_AES_256_GCM_SHA384               DH-2048 bits   256 bits
   TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             ECDH-256 bits  128 bits
   TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             ECDH-256 bits  256 bits
   TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256       -              256 bits
```

---

It's interesting that we now have a weaker cipher 'preferred'. Any theories on this @dyson?

**Comment by 8032** [comment]
I expect the preference will be set in terms of performance tradeoff as well as overall security.

The configuration looks much better, thanks for updated.

**Comment by dyson** [comment]
Yeah I believe it simply down to performance and that in _practice_ for example `TLS_DHE_RSA_WITH_AES_128_GCM_SHA256` and `TLS_DHE_RSA_WITH_AES_256_GCM_SHA384` are equally strong. A draupnir server doesn't get slammed like other services so we could change the ordering if we wanted to deviate from the recommendations. An ordered list I believe would be:
```
'TLS_AES_256_GCM_SHA384
TLS_AES_128_GCM_SHA256
TLS_CHACHA20_POLY1305_SHA256
DHE-RSA-AES256-GCM-SHA384
DHE-RSA-AES128-GCM-SHA256
ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-RSA-AES256-GCM-SHA384
ECDHE-ECDSA-AES128-GCM-SHA256
ECDHE-RSA-AES128-GCM-SHA256
ECDHE-ECDSA-CHACHA20-POLY1305
ECDHE-RSA-CHACHA20-POLY1305
```

I'm inclined to stick with the recommendations and leave the PR as is. Any thoughts? Otherwise I'll merge.

**Comment by benwh** [comment]
Makes sense! I'm good with merging

**Pull request merged**
